-- T&T Barateou — Etapa 6.18Y
-- Histórico permanente de envios. O cursor contínuo usa tt_app_state já existente.

create table if not exists public.tt_publication_history (
  id bigint generated by default as identity primary key,
  item_id text not null,
  product_id text,
  seller_id bigint,
  title text,
  price numeric,
  original_price numeric,
  discount numeric,
  affiliate_url text,
  tt_category_id text,
  group_name text,
  whatsapp_message_id text,
  sent_at timestamptz not null default now(),
  payload jsonb not null default '{}'::jsonb
);

create index if not exists tt_publication_history_product_sent_idx
  on public.tt_publication_history (product_id, sent_at desc);

create index if not exists tt_publication_history_item_sent_idx
  on public.tt_publication_history (item_id, sent_at desc);

create index if not exists tt_publication_history_sent_idx
  on public.tt_publication_history (sent_at desc);

alter table public.tt_publication_history enable row level security;

-- Sem policy pública. O backend usa SUPABASE_SECRET_KEY.
