-- T&T Barateou — Etapa 6.18Z
-- Banco de Reserva / fallback manual.

create table if not exists public.tt_fallback_links (
  id bigint generated by default as identity primary key,
  group_name text not null check (group_name in ('eletronicos', 'fitness', 'perfumes')),
  original_url text not null,
  product_id text,
  item_id text,
  current_item_id text,
  title text,
  price numeric,
  status text not null default 'available'
    check (status in ('available', 'claimed', 'queued', 'used', 'rejected', 'expired', 'duplicate', 'removed')),
  failure_reason text,
  metadata jsonb not null default '{}'::jsonb,
  added_at timestamptz not null default now(),
  claimed_at timestamptz,
  queued_at timestamptz,
  used_at timestamptz,
  last_checked_at timestamptz,
  updated_at timestamptz not null default now()
);

create index if not exists tt_fallback_links_group_status_added_idx
  on public.tt_fallback_links (group_name, status, added_at);

create index if not exists tt_fallback_links_current_item_idx
  on public.tt_fallback_links (current_item_id)
  where current_item_id is not null;

-- Impede a mesma URL ativa duas vezes no mesmo grupo, mas permite que o
-- usuário volte a adicioná-la no futuro após used/rejected/expired/removed.
create unique index if not exists tt_fallback_links_active_url_uidx
  on public.tt_fallback_links (group_name, original_url)
  where status in ('available', 'claimed', 'queued');

-- Evita estoque artificial duplicado do mesmo produto enquanto ele ainda
-- está aguardando uso.
create unique index if not exists tt_fallback_links_active_product_uidx
  on public.tt_fallback_links (group_name, product_id)
  where product_id is not null
    and status in ('available', 'claimed', 'queued');

alter table public.tt_fallback_links enable row level security;

-- Sem policies públicas: o acesso é somente server-side com
-- SUPABASE_SECRET_KEY, como o restante da fila T&T.

drop trigger if exists tt_fallback_links_set_updated_at
  on public.tt_fallback_links;

create trigger tt_fallback_links_set_updated_at
before update on public.tt_fallback_links
for each row
execute function public.tt_set_updated_at();
