import crypto from "node:crypto";
const COOKIE="tt_panel_session",TTL=12*60*60*1000;
function env(n){const v=String(process.env[n]||"").trim();if(!v){const e=new Error(`Variável ${n} não configurada.`);e.statusCode=503;throw e}return v}
function safe(a,b){a=Buffer.from(String(a||""));b=Buffer.from(String(b||""));return a.length===b.length&&crypto.timingSafeEqual(a,b)}
function sig(p){return crypto.createHmac("sha256",env("TT_PANEL_SESSION_SECRET")).update(p).digest("base64url")}
function token(){const p=Buffer.from(JSON.stringify({v:1,exp:Date.now()+TTL,n:crypto.randomBytes(12).toString("hex")})).toString("base64url");return `${p}.${sig(p)}`}
function cookies(req){const o={};for(const p of String(req.headers?.cookie||"").split(";")){const i=p.indexOf("=");if(i>0)o[p.slice(0,i).trim()]=decodeURIComponent(p.slice(i+1).trim())}return o}
function valid(req){const t=cookies(req)[COOKIE];if(!t)return false;const[p,s]=t.split(".");if(!p||!s||!safe(s,sig(p)))return false;try{const d=JSON.parse(Buffer.from(p,"base64url").toString("utf8"));return d.v===1&&Number(d.exp)>Date.now()}catch{return false}}
function sameOrigin(req){const o=String(req.headers?.origin||"");if(!o)return;const proto=String(req.headers["x-forwarded-proto"]||"https").split(",")[0].trim(),host=String(req.headers.host||"").trim();if(o!==`${proto}://${host}`){const e=new Error("Origem inválida.");e.statusCode=403;throw e}}
function base(req){const c=String(process.env.TT_PUBLIC_BASE_URL||"").trim().replace(/\/+$/,"");if(c)return /^https?:\/\//i.test(c)?c:`https://${c}`;const proto=String(req.headers["x-forwarded-proto"]||"https").split(",")[0].trim(),host=String(req.headers.host||"").trim();return `${proto}://${host}`}
async function json(r){try{return await r.json()}catch{return null}}
async function back(req,{action,method="GET",query={},body=null}){const u=new URL("/api/discover-bestsellers",base(req));u.searchParams.set("action",action);for(const[k,v]of Object.entries(query))if(v!==null&&v!==undefined&&v!=="")u.searchParams.set(k,String(v));const r=await fetch(u,{method,headers:{Accept:"application/json","Content-Type":"application/json","x-tt-admin-key":env("TT_QUEUE_ADMIN_KEY")},body:body===null?undefined:JSON.stringify(body)}),d=await json(r);if(!r.ok||d?.ok===false){const e=new Error(d?.error||d?.message||`Backend HTTP ${r.status}`);e.statusCode=r.status>=400?r.status:502;throw e}return d}
async function ml(req){const r=await fetch(new URL("/api/ml-status",base(req)),{headers:{Accept:"application/json"}});return await json(r)||{connected:false}}
function links(v){return [...new Set((Array.isArray(v)?v:String(v||"").split(/\s+/)).map(x=>String(x||"").trim()).filter(x=>/^https?:\/\//i.test(x)))].slice(0,20)}
async function dashboard(req){const[summary,queue,mlStatus]=await Promise.all([back(req,{action:"queue-summary"}),back(req,{action:"queue-list",query:{limit:50}}),ml(req)]);let perfumeAvailableCount=0;try{const r=await back(req,{action:"reserve-list",query:{group:"perfumes",status:"available",limit:100}});perfumeAvailableCount=Array.isArray(r.reserve)?r.reserve.length:0}catch{}return{ok:true,summary,queue,mlStatus,perfumeAvailableCount}}
async function reserveAdd(req){const b=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{}),group=String(b.group||"").toLowerCase(),ls=links(b.affiliateLinks||b.links);if(!["eletronicos","fitness","perfumes"].includes(group)){const e=new Error("Grupo inválido.");e.statusCode=400;throw e}if(!ls.length){const e=new Error("Envie pelo menos um link.");e.statusCode=400;throw e}const out=[];for(let i=0;i<ls.length;i+=10)out.push(await back(req,{action:"reserve-add",method:"POST",body:{group,affiliateLinks:ls.slice(i,i+10)}}));return{ok:out.every(x=>x.allSucceeded!==false),group,requestedCount:ls.length,addedCount:out.reduce((s,x)=>s+Number(x.addedCount||0),0),duplicateCount:out.reduce((s,x)=>s+Number(x.duplicateCount||0),0),failedCount:out.reduce((s,x)=>s+Number(x.failedCount||0),0),results:out.flatMap(x=>x.results||[])}}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store, max-age=0");try{const a=String(req.query?.action||"").toLowerCase();if(a==="login"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"Use POST."});sameOrigin(req);const b=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{});if(!safe(b.password,env("TT_PANEL_PASSWORD")))return res.status(401).json({ok:false,error:"Senha incorreta."});res.setHeader("Set-Cookie",`${COOKIE}=${encodeURIComponent(token())}; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=${Math.floor(TTL/1000)}`);return res.status(200).json({ok:true,authenticated:true})}if(a==="logout"){sameOrigin(req);res.setHeader("Set-Cookie",`${COOKIE}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`);return res.status(200).json({ok:true})}if(a==="session")return valid(req)?res.status(200).json({ok:true,authenticated:true}):res.status(401).json({ok:false,error:"Sessão não autenticada."});if(!valid(req))return res.status(401).json({ok:false,error:"Sessão do painel inválida ou expirada."});if(req.method==="POST")sameOrigin(req);if(a==="dashboard")return res.status(200).json(await dashboard(req));if(a==="reserve-list")return res.status(200).json(await back(req,{action:"reserve-list",query:{group:"perfumes",status:req.query?.status||"available",limit:100}}));if(a==="reserve-add"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"Use POST."});return res.status(200).json(await reserveAdd(req))}if(a==="reserve-remove"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"Use POST."});const b=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{}),id=Number(b.id);if(!Number.isInteger(id)||id<=0)return res.status(400).json({ok:false,error:"ID inválido."});return res.status(200).json(await back(req,{action:"reserve-remove",method:"POST",body:{id}}))}if(a==="discover"){if(req.method!=="POST")return res.status(405).json({ok:false,error:"Use POST."});const b=typeof req.body==="string"?JSON.parse(req.body||"{}"):(req.body||{}),group=String(b.group||"").toLowerCase();if(!["eletronicos","fitness"].includes(group))return res.status(400).json({ok:false,error:"Use eletronicos ou fitness."});return res.status(200).json(await back(req,{action:"continuous-discover",method:"POST",body:{group}}))}return res.status(404).json({ok:false,error:"Ação não encontrada."})}catch(e){return res.status(e?.statusCode||500).json({ok:false,error:e?.message||"Erro inesperado."})}}
